### ISSUE TITLE
Manage negative values

### ISSUE THREAD

**Issue by Laura930720** [asjadnaqvi/stata-treemap#1]
Is there a way to draw a treemap if I have both possitive and negative values? I think tableau send a message error and just delete the negative rows, I think in this case I  could work just with absolute values, but is there a way to manage negative ones just with the library treemap?

**Comment by asjadnaqvi** [comment]
Negative values should give an error. I will add this in. My suggestion would be to use absolute values and maybe add another category this differentiates positive and negative. So at least when you draw them, it shows the subcategories.

**Comment by asjadnaqvi** [comment]
added in v1.2
