### ISSUE TITLE
make -treemap- -labsplit- ready

### ISSUE THREAD

**Issue by mkaulisch** [asjadnaqvi/stata-treemap#11]
in treemap the display of the values is very important to me.
As the wrap-option is too strict in my usecase I tried -labsplit-. But the display of the values is not adjusted to those two line labels:
![grafik](https://github.com/user-attachments/assets/dfe981b1-a0cd-4250-9366-47ba958484c7)

**Comment by asjadnaqvi** [comment]
3x coffees per "on demand" feature requests ;)

**Comment by mkaulisch** [comment]
Thank you very much - that looks really cool now. Only for your information: I have contacted Stata Tech Support because the svg-export of the resulting graph does not respect the linewrapping. At least when I display the svg-file in MS Powerpoinmt or Inkscape.
