### ISSUE TITLE
class ColrSpace undefined

### ISSUE THREAD

**Issue by NPRCE** [asjadnaqvi/stata-treemap#12]
I have occupation-by-age cohorts for Finland and every time I try to run the treemap code, I get the following error: class ColrSpace undefined.

Essentially the code is trying to plot numbers of employees by each age category in a certain groups of occupation and the code looks like:

`import delimited https://statfin.stat.fi:443/PxWeb/sq/84c77e65-77b3-46ac-901f-384b0ff4d96f, varnames(2) clear`

* I did some data transformation to keep only a few level 4 occupations

`treemap total55plus2022employed , by( occupation ) colorby(occupation)`

I get the following error:

```
class ColrSpace undefined
(error occurred while loading colorpalette.ado)
r(3000);
```

Data is here: https://statfin.stat.fi/PxWeb/pxweb/en/StatFin/StatFin__tyokay/statfin_tyokay_pxt_115r.px/

**Comment by asjadnaqvi** [comment]
Update the packages, install `colrspace` and prepare the data:

```stata
** add packages. Run once or until the packages are updated.

/*
ssc install palettes, replace
ssc install colrspace, replace
ssc install moremata, replace
ssc install carryforward, replace  // for the data prep

net install graphfunctions, from("https://raw.githubusercontent.com/asjadnaqvi/stata-graphfunctions/main/installation/") replace // not currently on SSC
*/


*** get the data
import delimited "https://statfin.stat.fi:443/PxWeb/sq/84c77e65-77b3-46ac-901f-384b0ff4d96f", varnames(2) clear

// prepare the levels
gen code0 = ustrregexs(0) if ustrregexm(occupationalgroup, "^([0-9])\s")
gen occ0 = occupationalgroup if !missing(code0)

gen code1 = ustrregexs(0) if ustrregexm(occupationalgroup, "^([0-9][0-9])\s")
gen occ1 = occupationalgroup if !missing(code1)

gen code2 = ustrregexs(0) if ustrregexm(occupationalgroup, "^([0-9][0-9][0-9])\s")
gen occ2 = occupationalgroup if !missing(code2)

gen code3 = ustrregexs(0) if ustrregexm(occupationalgroup, "^([0-9][0-9][0-9][0-9])\s")
gen occ3 = occupationalgroup if !missing(code3)

gen code4 = ustrregexs(0) if ustrregexm(occupationalgroup, "^([0-9][0-9][0-9][0-9]\.)\s")
replace code4 = ustrregexs(0) if ustrregexm(occupationalgroup, "^([0-9][0-9][0-9][0-9][0-9])\s")
gen occ4 = occupationalgroup if !missing(code4)

gen id = _n

order id code* occ*
drop occupationalgroup

carryforward code0 occ0, replace


sort code0 id
by code0: carryforward code1 occ1, replace

sort code0 code1 id
by code0 code1: carryforward code2 occ2, replace

sort code0 code1 code2 id
by code0 code1 code2: carryforward code3 occ3, replace

sort code0 code1 code2 code3 id
by code0 code1 code2 code3: carryforward code4 occ4, replace

drop if code4==""


// plot the data. There is a string error with occ2, occ3 which I am checking
treemap totaltotal2022employed , by(occ0 occ1) wrap(40 20) addtitle titleprop labprop titlegap(0.2) ///
labcond(20000) labsize(1.6 1.6)
```

![treemap_test1](https://github.com/user-attachments/assets/3216b387-57b8-4637-81ef-7a2538fe3513)

**Comment by NPRCE** [comment]
Thanks for the quick response. While the code works well from the command bar, it does not if I run it from a .do file.

The second issue is that if I were to merge a dummy variable from a different data, I get the same issue as before and am unable to generate the graph.

I have attached the error message I get from running the .do file with no changes to your code, its the same error when I try to make any additional changes to the data i.e. merge, if statements using dummies etc.

![image](https://github.com/user-attachments/assets/a630f7da-138d-452e-8b84-85ed5427a28c)

**Comment by asjadnaqvi** [comment]
that is a `colrspace` issue that I cannot say much about but you can try the following. 

1. Check if there are multiple `colrspace` installations. Try `ado update, update`. 

2. 2Otherwise manually remove all colrspace files:

```
    c:\ado\plus\c\colrspace.sthlp
    c:\ado\plus\c\colrspace_source.sthlp
    c:\ado\plus\c\colrspace_library_namedcolors.sthlp
    c:\ado\plus\c\colrspace_library_palettes.sthlp
    c:\ado\plus\l\lcolrspace.mlib
```

and do a clean install

```
ssc install colrspace, replace
```

and hope it works!
