### ISSUE TITLE
noval option

### ISSUE THREAD

**Issue by NicolaTommasi8** [asjadnaqvi/stata-treemap#9]
Hi Asjad,

I don't understand the difference between the graphs generated by the following commands:

`treemap y_TOT, by(NUTS0) labsize(2.5) format(15.0fc) title("Population of European countries")`

`treemap y_TOT, by(NUTS0) labsize(2.5) title("Population of European countries") noval`

It's as if the noval option doesn't have any effect. These are the first 2 graphs

Thanks,
Nicola

**Comment by asjadnaqvi** [comment]
There is a bug in the code in how the `format()` option is defined with % missing and it is breaking the code. Will add better checks for this in the next update.

It should read:

```
treemap y_TOT, by(NUTS0) labsize(2.5) format(%15.0fc) title("Population of European countries")
```
